name: main

on:
  push:
    branches: [main, master]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      SHINY_APPS_IO: ${{ secrets.SHINY_APPS_IO }}
      APP_NAME: main
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2
      - name: Deploy app
        run: Rscript deploy.R
