name: pr

on:
  pull_request: {}
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SHINY_APPS_IO: ${{ secrets.SHINY_APPS_IO }}
      APP_NAME: dev
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2
      - name: Deploy app
        run: Rscript deploy.R
